### ISSUE TITLE
ng serve not working

### ISSUE THREAD

**Issue by re2005** [jonathan-casarrubias/ng2-service-events#1]
after run `npm install`

running `ng serve`

get this error:

```

Unable to find "@angular/cli" in devDependencies.

The package "angular-cli" has been deprecated and renamed to "@angular/cli".

Please take the following steps to avoid issues:
"npm uninstall --save-dev angular-cli"
"npm install --save-dev @angular/cli@latest"

The "defaults.prefix" and "defaults.sourceDir" properties of .angular-cli.json are deprecated in favor of "apps[0].root" and "apps[0].prefix". Please update in order to avoid errors in future versions of Angular CLI.
The "@angular/compiler-cli" package was not properly installed.
```

**Comment by jonathan-casarrubias** [comment]
Hey @re2005 thanks for reaching out,

I'm sorry this example is not working anymore, is a year old... but I can assume if you create a new angular project with the new @angular/cli and migrate the app inside it might work, I'll see if I can get some time to update this example, but honestly I'm a little overloaded right now.

Regards
Jon

**Comment by re2005** [comment]
Hey Jonathan,

Nice to hear from you.

Actually from that example I was able to do what I need, communicate
between two components, pretty simple and clean.

Thanks!



Kind Regards,
Renato Cardoso
